// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AddRoute provides a mock function with given fields: topic, callback
func (_m *Client) AddRoute(topic string, callback mqtt.MessageHandler) {
	_m.Called(topic, callback)
}

// Client_AddRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoute'
type Client_AddRoute_Call struct {
	*mock.Call
}

// AddRoute is a helper method to define mock.On call
//   - topic string
//   - callback mqtt.MessageHandler
func (_e *Client_Expecter) AddRoute(topic interface{}, callback interface{}) *Client_AddRoute_Call {
	return &Client_AddRoute_Call{Call: _e.mock.On("AddRoute", topic, callback)}
}

func (_c *Client_AddRoute_Call) Run(run func(topic string, callback mqtt.MessageHandler)) *Client_AddRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(mqtt.MessageHandler))
	})
	return _c
}

func (_c *Client_AddRoute_Call) Return() *Client_AddRoute_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_AddRoute_Call) RunAndReturn(run func(string, mqtt.MessageHandler)) *Client_AddRoute_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with given fields:
func (_m *Client) Connect() mqtt.Token {
	ret := _m.Called()

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func() mqtt.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Client_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Client_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *Client_Expecter) Connect() *Client_Connect_Call {
	return &Client_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *Client_Connect_Call) Run(run func()) *Client_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Connect_Call) Return(_a0 mqtt.Token) *Client_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Connect_Call) RunAndReturn(run func() mqtt.Token) *Client_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: quiesce
func (_m *Client) Disconnect(quiesce uint) {
	_m.Called(quiesce)
}

// Client_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Client_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - quiesce uint
func (_e *Client_Expecter) Disconnect(quiesce interface{}) *Client_Disconnect_Call {
	return &Client_Disconnect_Call{Call: _e.mock.On("Disconnect", quiesce)}
}

func (_c *Client_Disconnect_Call) Run(run func(quiesce uint)) *Client_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Client_Disconnect_Call) Return() *Client_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_Disconnect_Call) RunAndReturn(run func(uint)) *Client_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with given fields:
func (_m *Client) IsConnected() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Client_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type Client_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *Client_Expecter) IsConnected() *Client_IsConnected_Call {
	return &Client_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *Client_IsConnected_Call) Run(run func()) *Client_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_IsConnected_Call) Return(_a0 bool) *Client_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_IsConnected_Call) RunAndReturn(run func() bool) *Client_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnectionOpen provides a mock function with given fields:
func (_m *Client) IsConnectionOpen() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Client_IsConnectionOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnectionOpen'
type Client_IsConnectionOpen_Call struct {
	*mock.Call
}

// IsConnectionOpen is a helper method to define mock.On call
func (_e *Client_Expecter) IsConnectionOpen() *Client_IsConnectionOpen_Call {
	return &Client_IsConnectionOpen_Call{Call: _e.mock.On("IsConnectionOpen")}
}

func (_c *Client_IsConnectionOpen_Call) Run(run func()) *Client_IsConnectionOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_IsConnectionOpen_Call) Return(_a0 bool) *Client_IsConnectionOpen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_IsConnectionOpen_Call) RunAndReturn(run func() bool) *Client_IsConnectionOpen_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsReader provides a mock function with given fields:
func (_m *Client) OptionsReader() mqtt.ClientOptionsReader {
	ret := _m.Called()

	var r0 mqtt.ClientOptionsReader
	if rf, ok := ret.Get(0).(func() mqtt.ClientOptionsReader); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(mqtt.ClientOptionsReader)
	}

	return r0
}

// Client_OptionsReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsReader'
type Client_OptionsReader_Call struct {
	*mock.Call
}

// OptionsReader is a helper method to define mock.On call
func (_e *Client_Expecter) OptionsReader() *Client_OptionsReader_Call {
	return &Client_OptionsReader_Call{Call: _e.mock.On("OptionsReader")}
}

func (_c *Client_OptionsReader_Call) Run(run func()) *Client_OptionsReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_OptionsReader_Call) Return(_a0 mqtt.ClientOptionsReader) *Client_OptionsReader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_OptionsReader_Call) RunAndReturn(run func() mqtt.ClientOptionsReader) *Client_OptionsReader_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: topic, qos, retained, payload
func (_m *Client) Publish(topic string, qos byte, retained bool, payload interface{}) mqtt.Token {
	ret := _m.Called(topic, qos, retained, payload)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(string, byte, bool, interface{}) mqtt.Token); ok {
		r0 = rf(topic, qos, retained, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Client_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Client_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - retained bool
//   - payload interface{}
func (_e *Client_Expecter) Publish(topic interface{}, qos interface{}, retained interface{}, payload interface{}) *Client_Publish_Call {
	return &Client_Publish_Call{Call: _e.mock.On("Publish", topic, qos, retained, payload)}
}

func (_c *Client_Publish_Call) Run(run func(topic string, qos byte, retained bool, payload interface{})) *Client_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(byte), args[2].(bool), args[3].(interface{}))
	})
	return _c
}

func (_c *Client_Publish_Call) Return(_a0 mqtt.Token) *Client_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Publish_Call) RunAndReturn(run func(string, byte, bool, interface{}) mqtt.Token) *Client_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: topic, qos, callback
func (_m *Client) Subscribe(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _m.Called(topic, qos, callback)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = rf(topic, qos, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Client_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Client_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - callback mqtt.MessageHandler
func (_e *Client_Expecter) Subscribe(topic interface{}, qos interface{}, callback interface{}) *Client_Subscribe_Call {
	return &Client_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, qos, callback)}
}

func (_c *Client_Subscribe_Call) Run(run func(topic string, qos byte, callback mqtt.MessageHandler)) *Client_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(byte), args[2].(mqtt.MessageHandler))
	})
	return _c
}

func (_c *Client_Subscribe_Call) Return(_a0 mqtt.Token) *Client_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Subscribe_Call) RunAndReturn(run func(string, byte, mqtt.MessageHandler) mqtt.Token) *Client_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeMultiple provides a mock function with given fields: filters, callback
func (_m *Client) SubscribeMultiple(filters map[string]byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _m.Called(filters, callback)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(map[string]byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = rf(filters, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Client_SubscribeMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeMultiple'
type Client_SubscribeMultiple_Call struct {
	*mock.Call
}

// SubscribeMultiple is a helper method to define mock.On call
//   - filters map[string]byte
//   - callback mqtt.MessageHandler
func (_e *Client_Expecter) SubscribeMultiple(filters interface{}, callback interface{}) *Client_SubscribeMultiple_Call {
	return &Client_SubscribeMultiple_Call{Call: _e.mock.On("SubscribeMultiple", filters, callback)}
}

func (_c *Client_SubscribeMultiple_Call) Run(run func(filters map[string]byte, callback mqtt.MessageHandler)) *Client_SubscribeMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]byte), args[1].(mqtt.MessageHandler))
	})
	return _c
}

func (_c *Client_SubscribeMultiple_Call) Return(_a0 mqtt.Token) *Client_SubscribeMultiple_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_SubscribeMultiple_Call) RunAndReturn(run func(map[string]byte, mqtt.MessageHandler) mqtt.Token) *Client_SubscribeMultiple_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: topics
func (_m *Client) Unsubscribe(topics ...string) mqtt.Token {
	_va := make([]interface{}, len(topics))
	for _i := range topics {
		_va[_i] = topics[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(...string) mqtt.Token); ok {
		r0 = rf(topics...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Client_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Client_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - topics ...string
func (_e *Client_Expecter) Unsubscribe(topics ...interface{}) *Client_Unsubscribe_Call {
	return &Client_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe",
		append([]interface{}{}, topics...)...)}
}

func (_c *Client_Unsubscribe_Call) Run(run func(topics ...string)) *Client_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Client_Unsubscribe_Call) Return(_a0 mqtt.Token) *Client_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Unsubscribe_Call) RunAndReturn(run func(...string) mqtt.Token) *Client_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
